### PR TITLE
Id 28 fix helm chart

### PR DESCRIPTION
**Pull request by muhaluk322**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description

Fixed workspace vars, as it didn't match with values.yaml

## Jira
[Fix helm chart](https://sahaidakalana.atlassian.net/jira/software/c/projects/ID/boards/1?atlOrigin=eyJwIjoiaiIsImkiOiJlOWEwNThlNDZjN2E0MDM4ODMyNDFlMjFkNzBhYjVlMyJ9&cloudId=370bc990-3483-4321-99bf-1163ee88025e&selectedIssue=ID-28)

### CODE REVIEW

**Review by AlanaSahaidak — APPROVED** [review]
Good

**Review by ybeliche — CHANGES_REQUESTED** [review]
You need to provide 
```
imagePullSecrets:
  - name: yourname
```
  in the dev-01-gitea.yaml also, to be able to pull image from private repo

**Comment by muhaluk322** [comment]
added to workspace vars value `imagePullSecrets`

**Review by ybeliche — APPROVED** [review]
LGTM

**Pull request merged**
