### PR TITLE
Id 25 create kubernetes cluster using terraform

### PR DESCRIPTION
**Pull request by AlanaSahaidak**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This Terraform module sets up the Kubernetes cluster. At first, a new "workspace_vars" was added for the application Gitea. In cluster.tf, the cluster is configured, and in vpc.tf, the computing network for the new cluster and peering for two networks are configured.

## Jira
[Create Kubernetes cluster using Terraform](https://sahaidakalana.atlassian.net/browse/ID-25)

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### CODE REVIEW

**Review by ybeliche — CHANGES_REQUESTED** [review]
In vpc.tf, I think you forgot to add variables to names of "peering1" and "peering2", to bypass crash during the deployment to different environments

**Review by ybeliche — APPROVED** [review]
LGTM now

**Review by andrii-p-kovalchuk — APPROVED** [review]
LGTM

**Review by ybeliche — COMMENTED** [review]
Should we add seperate module for this infrastructure?

**Pull request merged**
