### PR TITLE
Terraform code for awx added.

### PR DESCRIPTION
**Pull request by andrii-p-kovalchuk**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Added terraform code for creating GKE cluster, deploying AWX with HELM.

### CODE REVIEW

**Review by ybeliche — COMMENTED** [review]
Variables absence means, that you won't be able to create infrastructure for different environments. You sure you want to add this?

**Review by muhaluk322 — APPROVED** [review]
LGTM

**Review by ybeliche — APPROVED** [review]
LGTM

**Comment by andrii-p-kovalchuk** [comment]
> Variables absence means, that you won't be able to create infrastructure for different environments. You sure you want to add this?

I think you are right. I'll do it

**Pull request merged**
